### ISSUE TITLE
SyntaxError: Expected ";;" but "(" found.

### ISSUE THREAD

**Issue by Osyotr** [ostis-dev/vs-code-ostis#11]
scp_program -> proc_get_edge_vertexes (*
	
	-> rrel_params: ... (*
		-> rrel_1: rrel_in: _edge;;
		-> rrel_2: rrel_out: _vertex1;;
		-> rrel_3: rrel_out: _vertex2;;
	*);;

![image](https://cloud.githubusercontent.com/assets/8740768/25044991/8349eb38-2132-11e7-86b2-491e5d74b303.png)

**Comment by deniskoronchik** [comment]
Need whole document for a test, seems that it doesn't support 
`x -> y: z: ...` correctly, but i need whole file to be sure.
You can attach it to this issue

**Comment by Osyotr** [comment]
[proc_find_carcass.txt](https://github.com/ostis-dev/vs-code-ostis/files/923817/proc_find_carcass.txt)
This one has the same issue

Also, it would be nice to highlight everything connected to SCP, like "rrel_fixed" or "rrel_scp_var"

**Comment by deniskoronchik** [comment]
@Osyotr You can provide list of requirede keynodes for scp there: #12

**Comment by deniskoronchik** [comment]
Fixed in #13 

@Osyotr you can update extension to 0.3.1
